# Generated by Django 2.2.4 on 2019-08-10 22:34

from django.db import migrations, models
import django.db.models.deletion
import rent.apps.billing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.IntegerField()),
                ('expense_type', models.CharField(max_length=255)),
                ('cost', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('recient', models.FileField(upload_to=rent.apps.billing.models.user_directory_path)),
                ('is_paid', models.BooleanField(default=False)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Tenant')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_id', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('active', models.CharField(max_length=3)),
                ('rent', models.IntegerField()),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Tenant')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Unit')),
            ],
        ),
    ]
